//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorderlandsShiftKeys.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShiftKey
    {
        public int Id { get; set; }
        public string ShiftKey { get; set; }
        public System.DateTime DateAdded { get; set; }
    }
}
